name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run unit tests
      run: |
        python -m pytest tests/unit -v --cov=src/

  integration:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup AWS resources
      env:
        TEST_DATA_BUCKET: ${{ secrets.TEST_DATA_BUCKET }}
        TEST_CHECKPOINT_BUCKET: ${{ secrets.TEST_CHECKPOINT_BUCKET }}
      run: |
        python scripts/setup_aws.py
    
    - name: Run integration tests
      env:
        INTEGRATION_TESTS: 'true'
        TEST_DATA_BUCKET: ${{ secrets.TEST_DATA_BUCKET }}
        TEST_CHECKPOINT_BUCKET: ${{ secrets.TEST_CHECKPOINT_BUCKET }}
      run: |
        python -m pytest tests/integration -v