name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy infrastructure
      run: python scripts/deploy.py --config config/production.yml
    
    - name: Verify deployment
      run: python scripts/verify_deployment.py --config config/production.yml
    
    - name: Tag successful deployment
      if: success()
      run: |
        echo "Deployment successful for version ${GITHUB_REF#refs/tags/}"
        echo "DEPLOY_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV